sudo: false

language: node_js

node_js:
  - "4"
  - "5"
  - "6"

cache:
  directories:
    - node_modules

script:
  - npm run test
  - npm run lint
  - npm run build

before_install:
  - "npm install -g npm@latest"
